modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
[[mods]]
modId="kellomod"
version="${file.jarVersion}"
displayName="Kello's Additions"
displayURL="https://github.com/Kello8/Kellos-Additions"
logoFile="logo.png"
authors="Kello"
description='''
A mod developed by Kello.
'''
[[dependencies.kellomod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.kellomod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
